### ISSUE TITLE
Conflicting peer dependency: react@17.0.2

### ISSUE THREAD

**Issue by chromato99** [KEA-ACCELER/A-Form_ReactJS_Front#37]
react-fade-in 라이브러리가 오래동안 관리되지 않아 현재의 react 버전을 지원하지 않는 문제가 있습니다.
간단한 라이브러리라 --force 옵션으로 설치해도 큰 문제는 없지만 문제를 야기할 수 있으니 수정하면 좋을것 같습니다.

해당 라이브러리: https://www.npmjs.com/package/react-fade-in
관련 이슈: https://github.com/gkaemmer/react-fade-in/issues/24

**Comment by SevngIl** [comment]
Done.
